### PR TITLE
Bump groovy version to 2.5.10-SNAPSHOT

### PR DESCRIPTION
**Pull request by rieske**
https://github.com/gradle/gradle/issues/10248#issuecomment-590712295

### CODE REVIEW

**Comment by lptr** [comment]
We shouldn't merge this as `SNAPSHOT`. Instead, we should run all the tests we think are relevant on the branch first, and if happy we should release `groovy-all-2.5.10` GA and use that.

I don't understand why this looks like an external contributor's PR. I'd say we should run `Ready for Release` in TeamCity before we move forward.

**Comment by lptr** [comment]
How can we verify JDK14 support?

**Comment by rieske** [comment]
That's the idea - run all the gradle/gradle tests with Groovy snapshot on a branch in order to:
1. Verify that nothing breaks with the new Groovy by running the full pipeline.
2. Run the tests against JDK14 using an experimental pipeline, see if there are any groovy specific breakages and take it from there. Currently it is the current version of Groovy that prevents Gradle even from starting (JDK14). Local ad-hoc experiments show that using this snapshot removes this initial obstacle and I would like to take this further and run the full pipeline.

In order to be able to run the gradle/gradle tests against this new version of Groovy, we need a distribution of groovy-all based on the latest snapshot.
Looking at the [history](https://github.com/gradle/gradle-groovy-all/commits/master/gradle.properties) in this repository, it looks like updating the version to snapshot and releasing a `groovy-all-1.3-newVersion-SNAPSHOT` was the way to go in the past.
The code in build.gradle suggests that if the Groovy version in use ends with -SNAPSHOT: https://github.com/gradle/gradle-groovy-all/blob/master/build.gradle#L13
then, the promotion job will also release a snapshot: https://github.com/gradle/gradle-groovy-all/blob/master/build.gradle#L209
The `Publish Gradle Groovy-all` job does not take a branch argument and looks to be configured to only publish from `master`.

**Comment by rieske** [comment]
On the other hand, I might be able to check in a locally published `groovy-all-1.3-2.5.10-SNAPSHOT` in a gradle/gradle branch, configure a local maven repo and take it from there.

**Comment by lptr** [comment]
Ah, I thought this was a PR in `grade/gradle` :) Sorry, do carry on :)

**Pull request merged**
